# -*- coding: utf-8 -*-
"""AULA R = DataMovie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbKWPrNxc37FrPPhSF6EyqpMcgZ_pOLw
"""

# Carregar o arquivo de texto em um dataframe
dados <- read.csv("movie.txt")

# Usando a função names()
colunas <- names(dados)
print(colunas)

# Visualizar as primeiras 5 linhas do resultado
print(head(dados, 2))

# Verificar a estrutura do dataframe
str(dados)

# Converter as colunas movieId e age para numérico
dados$movieId <- as.numeric(dados$movieId)
dados$age <- as.numeric(dados$age)

# Verificar a estrutura do dataframe após a conversão
str(dados)

# Excluir a primeira coluna
dados <- dados[, -1]

# Visualizar as primeiras 5 linhas do resultado
print(head(dados, 5))

# Ordenar o dataframe pelo valor da coluna "age"
dados <- dados[order(as.numeric(dados$age)), ]

# Visualizar as primeiras 5 linhas do resultado
print(head(dados, 10))

# Contar a frequência de cada valor único na coluna "age"
freq_age <- table(dados$age)

# Classificar as frequências em ordem decrescente
freq_age_sorted <- sort(freq_age, decreasing = TRUE)

# Selecionar os 10 números mais frequentes
top_10_numeros <- names(freq_age_sorted)[1:10]

# Obter as contagens dos 10 números mais frequentes
contagens_top_10 <- freq_age_sorted[1:10]

# Exibir os 10 números mais frequentes e suas contagens formatados como lista
cat("Top 10 números mais frequentes na coluna 'age' e suas contagens:\n")
for (i in 1:10) {
  cat("\n", i, ". Ano mais frequente: ", top_10_numeros[i], "\n")
  cat("   - Citado tantas vezes: ", contagens_top_10[i], "\n")
}

# Criar um dataframe com os dados dos 10 anos mais frequentes e suas contagens
dados_top_10 <- data.frame(Ano = top_10_numeros, Contagem = contagens_top_10)

# Exibir a tabela
print(dados_top_10)

# Dividir os gêneros em cada entrada e criar uma lista de todos os gêneros
todos_generos <- unlist(strsplit(dados$genres, "\\|"))

# Contar a frequência de cada gênero
freq_generos <- table(todos_generos)

# Ordenar os gêneros em ordem decrescente de frequência
freq_generos_ordenados <- sort(freq_generos, decreasing = TRUE)

# Selecionar os 10 gêneros mais citados
top_10_generos <- names(freq_generos_ordenados)[1:10]

# Obter as contagens dos 10 gêneros mais citados
contagens_top_10_generos <- freq_generos_ordenados[1:10]

# Criar um dataframe com os dados dos 10 gêneros mais citados e suas contagens
dados_top_10_generos <- data.frame(Gênero = top_10_generos, Contagem = contagens_top_10_generos)

# Exibir a tabela com os 10 gêneros mais citados
print(dados_top_10_generos)

# Encontrar o ano mais frequente
ano_mais_frequente <- names(freq_age_sorted)[1]

# Filtrar o dataframe para incluir apenas as entradas que correspondem ao ano mais frequente
dados_ano_mais_frequente <- dados[dados$age == ano_mais_frequente, ]

# Dividir os gêneros em cada entrada e criar uma lista de todos os gêneros para esse ano
todos_generos_ano_mais_frequente <- unlist(strsplit(dados_ano_mais_frequente$genres, "\\|"))

# Contar a frequência de cada gênero para esse ano
freq_generos_ano_mais_frequente <- table(todos_generos_ano_mais_frequente)

# Encontrar o gênero mais frequente para esse ano
genero_mais_frequente_ano_mais_frequente <- names(which.max(freq_generos_ano_mais_frequente))

# Verificar quantas vezes o gênero mais frequente ocorreu no ano mais frequente
freq_genero_mais_frequente_ano_mais_frequente <- freq_generos_ano_mais_frequente[genero_mais_frequente_ano_mais_frequente]

# Exibir o resultado
print(paste("No ano de", ano_mais_frequente, "foi o ano mais frequente, e nesse ano o genero mais frequente foi", genero_mais_frequente_ano_mais_frequente, "e ocorreu", freq_genero_mais_frequente_ano_mais_frequente, "vezes."))

# Filtrar o dataframe para incluir apenas os filmes de drama em 2013
filmes_drama_2013 <- subset(dados, grepl("Drama", genres) & age == "2013")

# Selecionar 10 filmes aleatórios (se quiser) ou os 10 primeiros
# Use sample_n(filmes_drama_2013, 10) para selecionar aleatoriamente
filmes_drama_2013_10 <- head(filmes_drama_2013, 10)

# Exibir o dataframe com os filmes de drama em 2013
print(filmes_drama_2013_10)

#Dataframe Criados para Analises dos Dados
#dados_top_10

#dados_top_10_generos

#filmes_drama_2013_10

install.packages("ggplot2")
library(ggplot2)

cores <- c(
  "#001F3F",  # Azul-marinho
  "#2ECC71",  # Verde-esmeralda
  "#C0392B",  # Vermelho-rubi
  "#F1C40F",  # Amarelo-ouro
  "#9B59B6",  # Roxo-ametista
  "#E67E22",  # Laranja-terracota
  "#1ABC9C",  # Turquesa
  "#FF007F",  # Rosa-choque
  "#A52A2A",  # Marrom-café
  "#EAEAEA"   # Cinza-pérola
)

"""# **Para o dataframe dados_top_10**"""

#Gráfico de Barras Horizontais

# Criar o gráfico de barras horizontais com suas cores personalizadas
ggplot(dados_top_10, aes(x = Ano, y = Contagem)) +
  geom_bar(stat = "identity", fill = cores) +  # Usando as cores personalizadas
  labs(title = "Top 10 Anos Mais Frequentes", x = "Ano", y = "Contagem") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Gráfico de Linhas

# Carregar a biblioteca ggplot2
library(ggplot2)

# Criar o gráfico de linhas
ggplot(dados_top_10, aes(x = Ano, y = Contagem)) +
  geom_line(aes(group = 1), color = cores) + # Adicionando group = 1
  geom_point(color = "blue") +
  labs(title = "Tendência dos 10 Anos Mais Frequentes ao Longo do Tempo", x = "Ano", y = "Contagem") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

"""# **Para o dataframe dados_top_10_generos**"""

# Ordenar o dataframe por contagem
dados_top_10_generos <- dados_top_10_generos[order(dados_top_10_generos$Contagem.Freq, decreasing = TRUE), ]

# Calcular o total de contagens
total_contagens <- sum(dados_top_10_generos$Contagem.Freq)

# Criar o gráfico de pizza com as contagens dos gêneros usando cores personalizadas
ggplot(dados_top_10_generos, aes(x = "", y = Contagem.Freq, fill = Gênero)) +
  geom_bar(stat = "identity") +
  coord_polar("y") +
  labs(title = "Distribuição dos 10 Gêneros Mais Citados", fill = "Gênero") +
  theme_void() +
  geom_text(aes(label = paste0(Gênero, "\n", scales::percent(Contagem.Freq/total_contagens))),
            position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = cores) +  # Usando cores personalizadas
  guides(fill = guide_legend(title = "Gênero", reverse = TRUE)) +
  theme(legend.position = "bottom")

# Ordenar o dataframe por contagem
dados_top_10_generos <- dados_top_10_generos[order(dados_top_10_generos$Contagem.Freq, decreasing = TRUE), ]

# Criar o gráfico de barras verticais com cores personalizadas
ggplot(dados_top_10_generos, aes(x = reorder(Gênero, Contagem.Freq), y = Contagem.Freq, fill = Gênero)) +
  geom_bar(stat = "identity", width = 0.7) +
  scale_fill_manual(values = cores) +  # Usando cores personalizadas
  labs(title = "Contagem dos 10 Gêneros Mais Citados", x = "Gênero", y = "Contagem") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = guide_legend(title = "Gênero", reverse = TRUE))

"""# **Para o dataframe filmes_drama_2013_10**"""

# Filtrar os filmes de drama em 2013
filmes_drama_2013 <- subset(dados, grepl("Drama", genres) & age == "2013")

# Dividir os gêneros em cada entrada
todos_generos <- unlist(strsplit(filmes_drama_2013$genres, "\\|"))

# Remover a categoria "Drama" dos gêneros
todos_generos <- todos_generos[todos_generos != "Drama"]

# Contar a frequência de cada gênero
freq_generos <- table(todos_generos)

# Converter em dataframe
dados_generos <- data.frame(Gênero = names(freq_generos), Contagem = as.numeric(freq_generos))

# Ordenar os gêneros por contagem
dados_generos <- dados_generos[order(dados_generos$Contagem, decreasing = TRUE), ]

# Criar o gráfico de barras empilhadas com ggplot2
ggplot(dados_generos, aes(x = reorder(Gênero, Contagem), y = Contagem, fill = Gênero)) +
  geom_bar(stat = "identity") +
  labs(title = "Frequência de Gêneros (exceto Drama) junto com Drama em 2013",
       x = "Gênero", y = "Contagem") +
  scale_fill_manual(values = rep("salmon", nrow(dados_generos))) +  # Repetindo a cor "salmon" para cada gênero
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Criar um novo dataframe com uma única linha para agrupar todos os pontos
grupo <- data.frame(Gênero = rep("Todos", nrow(dados_generos_sem_drama)), Contagem = mean(dados_generos_sem_drama$Contagem))

# Adicionar o novo dataframe ao dataframe original
dados_generos_sem_drama <- rbind(dados_generos_sem_drama, grupo)

# Criar o gráfico de dispersão com linha de ligação
ggplot(dados_generos_sem_drama, aes(x = Gênero, y = Contagem)) +
  geom_point() +
  geom_line(aes(group = 1)) +  # Define um grupo único para desenhar a linha
  labs(title = "Gráfico de Dispersão da Contagem de Gêneros (juntos de filmes de DRAMA em 2013)",
       x = "Gênero", y = "Contagem") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))