# -*- coding: utf-8 -*-
"""AULA R = Dados gov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Wqbc4C01RwNyRlARJwIKOu9u5acdhOr
"""

# Carregar o arquivo de texto em um dataframe
dados <- read.csv("dados_gasolina.txt", sep = ";", header = TRUE, row.names = NULL)

# Usando a função names()
colunas <- names(dados)
print(colunas)

# Visualizar as primeiras 5 linhas do resultado
print(head(dados, 2))

# Verificar a estrutura do dataframe
str(dados)

# Usando a função names()
cat("Nomes das Colunas:\n")
cat(paste(colunas, collapse = "\t"))
cat("\n")
cat(rep("=", 12), "\n") # Visualização melhorada com linha de separação

# Visualizar as primeiras 2 linhas do resultado
cat("\nPrimeiras 2 Linhas:\n")
print(head(dados, 2), row.names = FALSE)

cat("\n", rep("=", 12), "\n") # Visualização melhorada com linha de separação

# Verificar a estrutura do dataframe
cat("\nEstrutura do DataFrame:\n")
str(dados)

# Carregar as bibliotecas necessárias
library(dplyr) # Para manipulação de dados

# Converter a coluna "Valor.de.Venda" para numérico
dados$Valor.de.Venda <- as.numeric(gsub(",", ".", dados$Valor.de.Venda))

# Excluir a coluna "Data.da.Coleta"
dados <- select(dados, -Data.da.Coleta)

# Excluir a coluna "Unidade.de.Medida"
dados <- select(dados, -Unidade.de.Medida)

# Verificar novamente a estrutura do dataframe após as conversões
str(dados)

library(dplyr)

# Região que mais e menos comprou
regiao_mais_menos_compraram <- dados %>%
  group_by(Regiao) %>%
  summarise(total_vendas = n()) %>%
  arrange(desc(total_vendas)) %>%
  slice(c(1, n())) %>%
  mutate(mais_ou_menos = ifelse(row_number() == 1, "mais", "menos"))

# 5 Estados que mais compraram
estados_mais_compraram <- dados %>%
  group_by(Estado) %>%
  summarise(total_vendas = n()) %>%
  arrange(desc(total_vendas)) %>%
  top_n(5)

# 5 Municípios que mais compraram
municipios_mais_compraram <- dados %>%
  group_by(Municipio) %>%
  summarise(total_vendas = n()) %>%
  arrange(desc(total_vendas)) %>%
  top_n(5)

# Produtos mais e menos vendidos
produtos_mais_menos_vendidos <- dados %>%
  group_by(Produto) %>%
  summarise(total_vendas = n()) %>%
  arrange(total_vendas) %>%
  slice(c(1, n()))

# Separando produtos mais e menos vendidos
produtos_mais_vendidos <- produtos_mais_menos_vendidos %>%
  filter(total_vendas == max(total_vendas))

produtos_menos_vendidos <- produtos_mais_menos_vendidos %>%
  filter(total_vendas == min(total_vendas))

# Maior e menor valor de venda por produto
maior_menor_valor_venda <- dados %>%
  group_by(Produto) %>%
  summarise(maior_valor_venda = max(Valor.de.Venda),
            menor_valor_venda = min(Valor.de.Venda))

# Total de vendas de todas as bandeiras
total_vendas_bandeiras <- dados %>%
  group_by(Bandeira) %>%
  summarise(total_vendas = n()) %>%
  arrange(desc(total_vendas))

# Calculando as porcentagens
produtos_totais <- dados %>%
  group_by(Produto) %>%
  summarise(total_vendas = n()) %>%
  mutate(percentage = total_vendas / sum(total_vendas) * 100)

# Imprimir os dataframes
print("Região que mais e menos comprou:")
print(regiao_mais_menos_compraram)

print("\n5 Estados que mais compraram:")
print(estados_mais_compraram)

print("\n5 Municípios que mais compraram:")
print(municipios_mais_compraram)

print("\nProdutos mais vendidos:")
print(produtos_mais_vendidos)

print("\nProdutos menos vendidos:")
print(produtos_menos_vendidos)

print("\nMaior e menor valor de venda por produto:")
print(maior_menor_valor_venda)

print("\nBandeiras que mais comprou:")
print(total_vendas_bandeiras)

# Lista de cores
minha_paleta_cores <- c("#1D3557", "#E63946", "#A8DADC", "#457B9D", "#F1FAEE")

install.packages("ggplot2")
library(ggplot2)

#5 Estados que mais compraram:
# Gráfico de Barras Agrupadas
# Distribuição de Vendas

# Ordenar os estados pelo total de vendas (do menor para o maior)
estados_mais_compraram <- estados_mais_compraram %>%
  arrange(total_vendas)

ggplot(estados_mais_compraram, aes(x = reorder(Estado, total_vendas), y = total_vendas, fill = Estado)) +
  geom_col() +  # Usar geom_col() para barras
  geom_point(color = "black", size = 2) +  # Adicionar pontos
  geom_line(aes(group = 1), color = "black") +  # Adicionar linhas
  scale_fill_manual(values = minha_paleta_cores) +
  labs(title = "5 Estados que mais compraram",
       x = "Estado",
       y = "Total de vendas") +
  theme_minimal()

# Produtos mais e menos vendidos:
# Gráfico de Pizza
# Distribuição de Vendas

ggplot(produtos_totais, aes(x = "", y = percentage, fill = Produto)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(title = "Distribuição Percentual de Vendas por Produto") +
  scale_fill_manual(values = minha_paleta_cores) +  # Usando sua paleta de cores personalizada
  theme_void()  # Remove elementos de tema desnecessários

# Maior e menor valor de venda por produto:
# Gráfico de Barras Comparativo
# Variação de Preços.

ggplot(maior_menor_valor_venda, aes(x = Produto)) +
  geom_bar(aes(y = maior_valor_venda, fill = "Maior Valor de Venda"), stat = "identity", position = "dodge", width = 0.5) +
  geom_bar(aes(y = menor_valor_venda, fill = "Menor Valor de Venda"), stat = "identity", position = "dodge", width = 0.5) +
  labs(title = "Maior e menor valor de venda por produto",
       x = "Produto",
       y = "Valor de Venda",
       fill = "") +
  scale_fill_manual(values = minha_paleta_cores) +
  theme_minimal()

# Bandeiras que mais compraram
bandeiras_mais_comprou <- dados %>%
  group_by(Bandeira) %>%
  summarise(total_vendas = n()) %>%
  arrange(desc(total_vendas)) %>%
  top_n(2)


#Bandeiras que mais comprou:
ggplot(bandeiras_mais_comprou, aes(x = "", y = total_vendas, fill = Bandeira)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = minha_paleta_cores) +
  labs(title = "Bandeiras que mais compraram",
       fill = "Bandeira",
       y = NULL) +
  theme_void() +
  theme(legend.position = "bottom")

# Plotar o gráfico de pizza com nomes das regiões
ggplot(regiao_mais_menos_compraram, aes(x = "", y = total_vendas, fill = Regiao)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = minha_paleta_cores) +
  labs(title = "Região que mais e menos comprou",
       fill = "Região",
       y = NULL) +
  theme_void() +
  theme(legend.position = "bottom")

library(dplyr)
library(stringr)

# Remover caracteres problemáticos da coluna Bandeira
dados_limpos <- dados %>%
  mutate(Bandeira = str_replace_all(Bandeira, "[^[:alnum:] ]", ""))

# Contar o número de vezes que cada bandeira é citada
total_por_bandeira <- dados_limpos %>%
  count(Bandeira)

# Exibir o resultado
print(total_por_bandeira)

# Filtrar as 5 bandeiras que mais aparecem
top5_bandeiras <- total_por_bandeira %>%
  arrange(desc(n)) %>%
  slice(1:5)

# Criar o gráfico de dispersão
grafico_dispersao <- ggplot(total_por_bandeira, aes(x = Bandeira, y = n)) +
  geom_point() +  # Adicionar os pontos de dispersão
  geom_text(data = top5_bandeiras, aes(label = Bandeira), vjust = -0.5, size = 3.5, color = "red") +  # Adicionar rótulos para as 5 bandeiras que mais aparecem
  labs(x = "Bandeira", y = "Total de vezes citada", title = "Total de vezes que cada bandeira é citada") +  # Adicionar rótulos aos eixos e título
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotacionar os rótulos do eixo x

# Mostrar o gráfico de dispersão
print(grafico_dispersao)

#5 Municípios que mais compraram:

# Reordenar os municípios pelo total de vendas (do maior para o menor)
municipios_mais_compraram <- municipios_mais_compraram %>%
  arrange(desc(total_vendas))

# Criar o gráfico de funil
ggplot(municipios_mais_compraram, aes(x = reorder(Municipio, -total_vendas), y = total_vendas, fill = Municipio)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = minha_paleta_cores) +
  labs(title = "5 Municípios que mais compraram",
       x = "Município",
       y = "Total de Vendas") +
  theme_minimal() +
  theme(legend.position = "none") +  # Removendo a legenda
  coord_flip()  # Inverter a orientação do gráfico para melhor visualização