{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Atividade 3 programacao em R"
      ],
      "metadata": {
        "id": "Ovcn59TZLl2B"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 21,
      "metadata": {
        "id": "p43iMUgaLHiD"
      },
      "outputs": [],
      "source": [
        "dados <- read.csv(\"movie.csv\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "View (dados)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "8vWea0d2Ly2B",
        "outputId": "67658b1f-8074-4822-ca38-ab56ccce59d8"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "      movieId title                                                          \n",
              "1      1      Toy Story (1995)                                               \n",
              "2      2      Jumanji (1995)                                                 \n",
              "3      3      Grumpier Old Men (1995)                                        \n",
              "4      4      Waiting to Exhale (1995)                                       \n",
              "5      5      Father of the Bride Part II (1995)                             \n",
              "6      6      Heat (1995)                                                    \n",
              "7      7      Sabrina (1995)                                                 \n",
              "8      8      Tom and Huck (1995)                                            \n",
              "9      9      Sudden Death (1995)                                            \n",
              "10    10      GoldenEye (1995)                                               \n",
              "11    11      American President, The (1995)                                 \n",
              "12    12      Dracula: Dead and Loving It (1995)                             \n",
              "13    13      Balto (1995)                                                   \n",
              "14    14      Nixon (1995)                                                   \n",
              "15    15      Cutthroat Island (1995)                                        \n",
              "16    16      Casino (1995)                                                  \n",
              "17    17      Sense and Sensibility (1995)                                   \n",
              "18    18      Four Rooms (1995)                                              \n",
              "19    19      Ace Ventura: When Nature Calls (1995)                          \n",
              "20    20      Money Train (1995)                                             \n",
              "21    21      Get Shorty (1995)                                              \n",
              "22    22      Copycat (1995)                                                 \n",
              "23    23      Assassins (1995)                                               \n",
              "24    24      Powder (1995)                                                  \n",
              "25    25      Leaving Las Vegas (1995)                                       \n",
              "26    26      Othello (1995)                                                 \n",
              "27    27      Now and Then (1995)                                            \n",
              "28    28      Persuasion (1995)                                              \n",
              "29    29      City of Lost Children, The (Cité des enfants perdus, La) (1995)\n",
              "30    30      Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)           \n",
              "⋮     ⋮       ⋮                                                              \n",
              "27249 131146  Werner - Volles Rooäää (1999)                                  \n",
              "27250 131148  What A Man (2011)                                              \n",
              "27251 131150  7 Dwarves: The Forest Is Not Enough (2006)                     \n",
              "27252 131152  The Fat Spy (1966)                                             \n",
              "27253 131154  Die Bademeister – Weiber, saufen, Leben retten (1999)          \n",
              "27254 131156  Ants in the Pants 2 (2002)                                     \n",
              "27255 131158  Manta, Manta (1991)                                            \n",
              "27256 131160  Oscar and the Lady in Pink (2009)                              \n",
              "27257 131162  Por un puñado de besos (2014)                                  \n",
              "27258 131164  Vietnam in HD (2011)                                           \n",
              "27259 131166  WWII IN HD (2009)                                              \n",
              "27260 131168  Phoenix (2014)                                                 \n",
              "27261 131170  Parallels (2015)                                               \n",
              "27262 131172  Closed Curtain (2013)                                          \n",
              "27263 131174  Gentlemen (2014)                                               \n",
              "27264 131176  A Second Chance (2014)                                         \n",
              "27265 131180  Dead Rising: Watchtower (2015)                                 \n",
              "27266 131231  Standby (2014)                                                 \n",
              "27267 131237  What Men Talk About (2010)                                     \n",
              "27268 131239  Three Quarter Moon (2011)                                      \n",
              "27269 131241  Ants in the Pants (2000)                                       \n",
              "27270 131243  Werner - Gekotzt wird später (2003)                            \n",
              "27271 131248  Brother Bear 2 (2006)                                          \n",
              "27272 131250  No More School (2000)                                          \n",
              "27273 131252  Forklift Driver Klaus: The First Day on the Job (2001)         \n",
              "27274 131254  Kein Bund für's Leben (2007)                                   \n",
              "27275 131256  Feuer, Eis & Dosenbier (2002)                                  \n",
              "27276 131258  The Pirates (2014)                                             \n",
              "27277 131260  Rentun Ruusu (2001)                                            \n",
              "27278 131262  Innocence (2014)                                               \n",
              "      genres                                     \n",
              "1     Adventure|Animation|Children|Comedy|Fantasy\n",
              "2     Adventure|Children|Fantasy                 \n",
              "3     Comedy|Romance                             \n",
              "4     Comedy|Drama|Romance                       \n",
              "5     Comedy                                     \n",
              "6     Action|Crime|Thriller                      \n",
              "7     Comedy|Romance                             \n",
              "8     Adventure|Children                         \n",
              "9     Action                                     \n",
              "10    Action|Adventure|Thriller                  \n",
              "11    Comedy|Drama|Romance                       \n",
              "12    Comedy|Horror                              \n",
              "13    Adventure|Animation|Children               \n",
              "14    Drama                                      \n",
              "15    Action|Adventure|Romance                   \n",
              "16    Crime|Drama                                \n",
              "17    Drama|Romance                              \n",
              "18    Comedy                                     \n",
              "19    Comedy                                     \n",
              "20    Action|Comedy|Crime|Drama|Thriller         \n",
              "21    Comedy|Crime|Thriller                      \n",
              "22    Crime|Drama|Horror|Mystery|Thriller        \n",
              "23    Action|Crime|Thriller                      \n",
              "24    Drama|Sci-Fi                               \n",
              "25    Drama|Romance                              \n",
              "26    Drama                                      \n",
              "27    Children|Drama                             \n",
              "28    Drama|Romance                              \n",
              "29    Adventure|Drama|Fantasy|Mystery|Sci-Fi     \n",
              "30    Crime|Drama                                \n",
              "⋮     ⋮                                          \n",
              "27249 Animation|Comedy                           \n",
              "27250 Comedy|Romance                             \n",
              "27251 Comedy                                     \n",
              "27252 Comedy                                     \n",
              "27253 Comedy                                     \n",
              "27254 Comedy                                     \n",
              "27255 Comedy                                     \n",
              "27256 Drama                                      \n",
              "27257 Drama|Romance                              \n",
              "27258 War                                        \n",
              "27259 (no genres listed)                         \n",
              "27260 Drama                                      \n",
              "27261 Sci-Fi                                     \n",
              "27262 (no genres listed)                         \n",
              "27263 Drama|Romance|Thriller                     \n",
              "27264 Drama                                      \n",
              "27265 Action|Horror|Thriller                     \n",
              "27266 Comedy|Romance                             \n",
              "27267 Comedy                                     \n",
              "27268 Comedy|Drama                               \n",
              "27269 Comedy|Romance                             \n",
              "27270 Animation|Comedy                           \n",
              "27271 Adventure|Animation|Children|Comedy|Fantasy\n",
              "27272 Comedy                                     \n",
              "27273 Comedy|Horror                              \n",
              "27274 Comedy                                     \n",
              "27275 Comedy                                     \n",
              "27276 Adventure                                  \n",
              "27277 (no genres listed)                         \n",
              "27278 Adventure|Fantasy|Horror                   "
            ],
            "text/html": [
              "<table class=\"dataframe\">\n",
              "<caption>A data.frame: 27278 × 3</caption>\n",
              "<thead>\n",
              "\t<tr><th scope=col>movieId</th><th scope=col>title</th><th scope=col>genres</th></tr>\n",
              "\t<tr><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;chr&gt;</th></tr>\n",
              "</thead>\n",
              "<tbody>\n",
              "\t<tr><td> 1</td><td>Toy Story (1995)                                               </td><td>Adventure|Animation|Children|Comedy|Fantasy</td></tr>\n",
              "\t<tr><td> 2</td><td>Jumanji (1995)                                                 </td><td>Adventure|Children|Fantasy                 </td></tr>\n",
              "\t<tr><td> 3</td><td>Grumpier Old Men (1995)                                        </td><td>Comedy|Romance                             </td></tr>\n",
              "\t<tr><td> 4</td><td>Waiting to Exhale (1995)                                       </td><td>Comedy|Drama|Romance                       </td></tr>\n",
              "\t<tr><td> 5</td><td>Father of the Bride Part II (1995)                             </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td> 6</td><td>Heat (1995)                                                    </td><td>Action|Crime|Thriller                      </td></tr>\n",
              "\t<tr><td> 7</td><td>Sabrina (1995)                                                 </td><td>Comedy|Romance                             </td></tr>\n",
              "\t<tr><td> 8</td><td>Tom and Huck (1995)                                            </td><td>Adventure|Children                         </td></tr>\n",
              "\t<tr><td> 9</td><td>Sudden Death (1995)                                            </td><td>Action                                     </td></tr>\n",
              "\t<tr><td>10</td><td>GoldenEye (1995)                                               </td><td>Action|Adventure|Thriller                  </td></tr>\n",
              "\t<tr><td>11</td><td>American President, The (1995)                                 </td><td>Comedy|Drama|Romance                       </td></tr>\n",
              "\t<tr><td>12</td><td>Dracula: Dead and Loving It (1995)                             </td><td>Comedy|Horror                              </td></tr>\n",
              "\t<tr><td>13</td><td>Balto (1995)                                                   </td><td>Adventure|Animation|Children               </td></tr>\n",
              "\t<tr><td>14</td><td>Nixon (1995)                                                   </td><td>Drama                                      </td></tr>\n",
              "\t<tr><td>15</td><td>Cutthroat Island (1995)                                        </td><td>Action|Adventure|Romance                   </td></tr>\n",
              "\t<tr><td>16</td><td>Casino (1995)                                                  </td><td>Crime|Drama                                </td></tr>\n",
              "\t<tr><td>17</td><td>Sense and Sensibility (1995)                                   </td><td>Drama|Romance                              </td></tr>\n",
              "\t<tr><td>18</td><td>Four Rooms (1995)                                              </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>19</td><td>Ace Ventura: When Nature Calls (1995)                          </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>20</td><td>Money Train (1995)                                             </td><td>Action|Comedy|Crime|Drama|Thriller         </td></tr>\n",
              "\t<tr><td>21</td><td>Get Shorty (1995)                                              </td><td>Comedy|Crime|Thriller                      </td></tr>\n",
              "\t<tr><td>22</td><td>Copycat (1995)                                                 </td><td>Crime|Drama|Horror|Mystery|Thriller        </td></tr>\n",
              "\t<tr><td>23</td><td>Assassins (1995)                                               </td><td>Action|Crime|Thriller                      </td></tr>\n",
              "\t<tr><td>24</td><td>Powder (1995)                                                  </td><td>Drama|Sci-Fi                               </td></tr>\n",
              "\t<tr><td>25</td><td>Leaving Las Vegas (1995)                                       </td><td>Drama|Romance                              </td></tr>\n",
              "\t<tr><td>26</td><td>Othello (1995)                                                 </td><td>Drama                                      </td></tr>\n",
              "\t<tr><td>27</td><td>Now and Then (1995)                                            </td><td>Children|Drama                             </td></tr>\n",
              "\t<tr><td>28</td><td>Persuasion (1995)                                              </td><td>Drama|Romance                              </td></tr>\n",
              "\t<tr><td>29</td><td>City of Lost Children, The (Cité des enfants perdus, La) (1995)</td><td>Adventure|Drama|Fantasy|Mystery|Sci-Fi     </td></tr>\n",
              "\t<tr><td>30</td><td>Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)           </td><td>Crime|Drama                                </td></tr>\n",
              "\t<tr><td>⋮</td><td>⋮</td><td>⋮</td></tr>\n",
              "\t<tr><td>131146</td><td>Werner - Volles Rooäää (1999)                         </td><td>Animation|Comedy                           </td></tr>\n",
              "\t<tr><td>131148</td><td>What A Man (2011)                                     </td><td>Comedy|Romance                             </td></tr>\n",
              "\t<tr><td>131150</td><td>7 Dwarves: The Forest Is Not Enough (2006)            </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131152</td><td>The Fat Spy (1966)                                    </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131154</td><td>Die Bademeister – Weiber, saufen, Leben retten (1999) </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131156</td><td>Ants in the Pants 2 (2002)                            </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131158</td><td>Manta, Manta (1991)                                   </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131160</td><td>Oscar and the Lady in Pink (2009)                     </td><td>Drama                                      </td></tr>\n",
              "\t<tr><td>131162</td><td>Por un puñado de besos (2014)                         </td><td>Drama|Romance                              </td></tr>\n",
              "\t<tr><td>131164</td><td>Vietnam in HD (2011)                                  </td><td>War                                        </td></tr>\n",
              "\t<tr><td>131166</td><td>WWII IN HD (2009)                                     </td><td>(no genres listed)                         </td></tr>\n",
              "\t<tr><td>131168</td><td>Phoenix (2014)                                        </td><td>Drama                                      </td></tr>\n",
              "\t<tr><td>131170</td><td>Parallels (2015)                                      </td><td>Sci-Fi                                     </td></tr>\n",
              "\t<tr><td>131172</td><td>Closed Curtain (2013)                                 </td><td>(no genres listed)                         </td></tr>\n",
              "\t<tr><td>131174</td><td>Gentlemen (2014)                                      </td><td>Drama|Romance|Thriller                     </td></tr>\n",
              "\t<tr><td>131176</td><td>A Second Chance (2014)                                </td><td>Drama                                      </td></tr>\n",
              "\t<tr><td>131180</td><td>Dead Rising: Watchtower (2015)                        </td><td>Action|Horror|Thriller                     </td></tr>\n",
              "\t<tr><td>131231</td><td>Standby (2014)                                        </td><td>Comedy|Romance                             </td></tr>\n",
              "\t<tr><td>131237</td><td>What Men Talk About (2010)                            </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131239</td><td>Three Quarter Moon (2011)                             </td><td>Comedy|Drama                               </td></tr>\n",
              "\t<tr><td>131241</td><td>Ants in the Pants (2000)                              </td><td>Comedy|Romance                             </td></tr>\n",
              "\t<tr><td>131243</td><td>Werner - Gekotzt wird später (2003)                   </td><td>Animation|Comedy                           </td></tr>\n",
              "\t<tr><td>131248</td><td>Brother Bear 2 (2006)                                 </td><td>Adventure|Animation|Children|Comedy|Fantasy</td></tr>\n",
              "\t<tr><td>131250</td><td>No More School (2000)                                 </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131252</td><td>Forklift Driver Klaus: The First Day on the Job (2001)</td><td>Comedy|Horror                              </td></tr>\n",
              "\t<tr><td>131254</td><td>Kein Bund für's Leben (2007)                          </td><td>Comedy                                     </td></tr>\n",
              "\t<tr><td>131256</td><td><span style=white-space:pre-wrap>Feuer, Eis &amp; Dosenbier (2002)                         </span></td><td><span style=white-space:pre-wrap>Comedy                                     </span></td></tr>\n",
              "\t<tr><td>131258</td><td>The Pirates (2014)                                    </td><td>Adventure                                  </td></tr>\n",
              "\t<tr><td>131260</td><td>Rentun Ruusu (2001)                                   </td><td>(no genres listed)                         </td></tr>\n",
              "\t<tr><td>131262</td><td>Innocence (2014)                                      </td><td>Adventure|Fantasy|Horror                   </td></tr>\n",
              "</tbody>\n",
              "</table>\n"
            ],
            "text/markdown": "\nA data.frame: 27278 × 3\n\n| movieId &lt;int&gt; | title &lt;chr&gt; | genres &lt;chr&gt; |\n|---|---|---|\n|  1 | Toy Story (1995)                                                | Adventure|Animation|Children|Comedy|Fantasy |\n|  2 | Jumanji (1995)                                                  | Adventure|Children|Fantasy                  |\n|  3 | Grumpier Old Men (1995)                                         | Comedy|Romance                              |\n|  4 | Waiting to Exhale (1995)                                        | Comedy|Drama|Romance                        |\n|  5 | Father of the Bride Part II (1995)                              | Comedy                                      |\n|  6 | Heat (1995)                                                     | Action|Crime|Thriller                       |\n|  7 | Sabrina (1995)                                                  | Comedy|Romance                              |\n|  8 | Tom and Huck (1995)                                             | Adventure|Children                          |\n|  9 | Sudden Death (1995)                                             | Action                                      |\n| 10 | GoldenEye (1995)                                                | Action|Adventure|Thriller                   |\n| 11 | American President, The (1995)                                  | Comedy|Drama|Romance                        |\n| 12 | Dracula: Dead and Loving It (1995)                              | Comedy|Horror                               |\n| 13 | Balto (1995)                                                    | Adventure|Animation|Children                |\n| 14 | Nixon (1995)                                                    | Drama                                       |\n| 15 | Cutthroat Island (1995)                                         | Action|Adventure|Romance                    |\n| 16 | Casino (1995)                                                   | Crime|Drama                                 |\n| 17 | Sense and Sensibility (1995)                                    | Drama|Romance                               |\n| 18 | Four Rooms (1995)                                               | Comedy                                      |\n| 19 | Ace Ventura: When Nature Calls (1995)                           | Comedy                                      |\n| 20 | Money Train (1995)                                              | Action|Comedy|Crime|Drama|Thriller          |\n| 21 | Get Shorty (1995)                                               | Comedy|Crime|Thriller                       |\n| 22 | Copycat (1995)                                                  | Crime|Drama|Horror|Mystery|Thriller         |\n| 23 | Assassins (1995)                                                | Action|Crime|Thriller                       |\n| 24 | Powder (1995)                                                   | Drama|Sci-Fi                                |\n| 25 | Leaving Las Vegas (1995)                                        | Drama|Romance                               |\n| 26 | Othello (1995)                                                  | Drama                                       |\n| 27 | Now and Then (1995)                                             | Children|Drama                              |\n| 28 | Persuasion (1995)                                               | Drama|Romance                               |\n| 29 | City of Lost Children, The (Cité des enfants perdus, La) (1995) | Adventure|Drama|Fantasy|Mystery|Sci-Fi      |\n| 30 | Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)            | Crime|Drama                                 |\n| ⋮ | ⋮ | ⋮ |\n| 131146 | Werner - Volles Rooäää (1999)                          | Animation|Comedy                            |\n| 131148 | What A Man (2011)                                      | Comedy|Romance                              |\n| 131150 | 7 Dwarves: The Forest Is Not Enough (2006)             | Comedy                                      |\n| 131152 | The Fat Spy (1966)                                     | Comedy                                      |\n| 131154 | Die Bademeister – Weiber, saufen, Leben retten (1999)  | Comedy                                      |\n| 131156 | Ants in the Pants 2 (2002)                             | Comedy                                      |\n| 131158 | Manta, Manta (1991)                                    | Comedy                                      |\n| 131160 | Oscar and the Lady in Pink (2009)                      | Drama                                       |\n| 131162 | Por un puñado de besos (2014)                          | Drama|Romance                               |\n| 131164 | Vietnam in HD (2011)                                   | War                                         |\n| 131166 | WWII IN HD (2009)                                      | (no genres listed)                          |\n| 131168 | Phoenix (2014)                                         | Drama                                       |\n| 131170 | Parallels (2015)                                       | Sci-Fi                                      |\n| 131172 | Closed Curtain (2013)                                  | (no genres listed)                          |\n| 131174 | Gentlemen (2014)                                       | Drama|Romance|Thriller                      |\n| 131176 | A Second Chance (2014)                                 | Drama                                       |\n| 131180 | Dead Rising: Watchtower (2015)                         | Action|Horror|Thriller                      |\n| 131231 | Standby (2014)                                         | Comedy|Romance                              |\n| 131237 | What Men Talk About (2010)                             | Comedy                                      |\n| 131239 | Three Quarter Moon (2011)                              | Comedy|Drama                                |\n| 131241 | Ants in the Pants (2000)                               | Comedy|Romance                              |\n| 131243 | Werner - Gekotzt wird später (2003)                    | Animation|Comedy                            |\n| 131248 | Brother Bear 2 (2006)                                  | Adventure|Animation|Children|Comedy|Fantasy |\n| 131250 | No More School (2000)                                  | Comedy                                      |\n| 131252 | Forklift Driver Klaus: The First Day on the Job (2001) | Comedy|Horror                               |\n| 131254 | Kein Bund für's Leben (2007)                           | Comedy                                      |\n| 131256 | Feuer, Eis &amp; Dosenbier (2002)                          | Comedy                                      |\n| 131258 | The Pirates (2014)                                     | Adventure                                   |\n| 131260 | Rentun Ruusu (2001)                                    | (no genres listed)                          |\n| 131262 | Innocence (2014)                                       | Adventure|Fantasy|Horror                    |\n\n",
            "text/latex": "A data.frame: 27278 × 3\n\\begin{tabular}{lll}\n movieId & title & genres\\\\\n <int> & <chr> & <chr>\\\\\n\\hline\n\t  1 & Toy Story (1995)                                                & Adventure\\textbar{}Animation\\textbar{}Children\\textbar{}Comedy\\textbar{}Fantasy\\\\\n\t  2 & Jumanji (1995)                                                  & Adventure\\textbar{}Children\\textbar{}Fantasy                 \\\\\n\t  3 & Grumpier Old Men (1995)                                         & Comedy\\textbar{}Romance                             \\\\\n\t  4 & Waiting to Exhale (1995)                                        & Comedy\\textbar{}Drama\\textbar{}Romance                       \\\\\n\t  5 & Father of the Bride Part II (1995)                              & Comedy                                     \\\\\n\t  6 & Heat (1995)                                                     & Action\\textbar{}Crime\\textbar{}Thriller                      \\\\\n\t  7 & Sabrina (1995)                                                  & Comedy\\textbar{}Romance                             \\\\\n\t  8 & Tom and Huck (1995)                                             & Adventure\\textbar{}Children                         \\\\\n\t  9 & Sudden Death (1995)                                             & Action                                     \\\\\n\t 10 & GoldenEye (1995)                                                & Action\\textbar{}Adventure\\textbar{}Thriller                  \\\\\n\t 11 & American President, The (1995)                                  & Comedy\\textbar{}Drama\\textbar{}Romance                       \\\\\n\t 12 & Dracula: Dead and Loving It (1995)                              & Comedy\\textbar{}Horror                              \\\\\n\t 13 & Balto (1995)                                                    & Adventure\\textbar{}Animation\\textbar{}Children               \\\\\n\t 14 & Nixon (1995)                                                    & Drama                                      \\\\\n\t 15 & Cutthroat Island (1995)                                         & Action\\textbar{}Adventure\\textbar{}Romance                   \\\\\n\t 16 & Casino (1995)                                                   & Crime\\textbar{}Drama                                \\\\\n\t 17 & Sense and Sensibility (1995)                                    & Drama\\textbar{}Romance                              \\\\\n\t 18 & Four Rooms (1995)                                               & Comedy                                     \\\\\n\t 19 & Ace Ventura: When Nature Calls (1995)                           & Comedy                                     \\\\\n\t 20 & Money Train (1995)                                              & Action\\textbar{}Comedy\\textbar{}Crime\\textbar{}Drama\\textbar{}Thriller         \\\\\n\t 21 & Get Shorty (1995)                                               & Comedy\\textbar{}Crime\\textbar{}Thriller                      \\\\\n\t 22 & Copycat (1995)                                                  & Crime\\textbar{}Drama\\textbar{}Horror\\textbar{}Mystery\\textbar{}Thriller        \\\\\n\t 23 & Assassins (1995)                                                & Action\\textbar{}Crime\\textbar{}Thriller                      \\\\\n\t 24 & Powder (1995)                                                   & Drama\\textbar{}Sci-Fi                               \\\\\n\t 25 & Leaving Las Vegas (1995)                                        & Drama\\textbar{}Romance                              \\\\\n\t 26 & Othello (1995)                                                  & Drama                                      \\\\\n\t 27 & Now and Then (1995)                                             & Children\\textbar{}Drama                             \\\\\n\t 28 & Persuasion (1995)                                               & Drama\\textbar{}Romance                              \\\\\n\t 29 & City of Lost Children, The (Cité des enfants perdus, La) (1995) & Adventure\\textbar{}Drama\\textbar{}Fantasy\\textbar{}Mystery\\textbar{}Sci-Fi     \\\\\n\t 30 & Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)            & Crime\\textbar{}Drama                                \\\\\n\t ⋮ & ⋮ & ⋮\\\\\n\t 131146 & Werner - Volles Rooäää (1999)                          & Animation\\textbar{}Comedy                           \\\\\n\t 131148 & What A Man (2011)                                      & Comedy\\textbar{}Romance                             \\\\\n\t 131150 & 7 Dwarves: The Forest Is Not Enough (2006)             & Comedy                                     \\\\\n\t 131152 & The Fat Spy (1966)                                     & Comedy                                     \\\\\n\t 131154 & Die Bademeister – Weiber, saufen, Leben retten (1999)  & Comedy                                     \\\\\n\t 131156 & Ants in the Pants 2 (2002)                             & Comedy                                     \\\\\n\t 131158 & Manta, Manta (1991)                                    & Comedy                                     \\\\\n\t 131160 & Oscar and the Lady in Pink (2009)                      & Drama                                      \\\\\n\t 131162 & Por un puñado de besos (2014)                          & Drama\\textbar{}Romance                              \\\\\n\t 131164 & Vietnam in HD (2011)                                   & War                                        \\\\\n\t 131166 & WWII IN HD (2009)                                      & (no genres listed)                         \\\\\n\t 131168 & Phoenix (2014)                                         & Drama                                      \\\\\n\t 131170 & Parallels (2015)                                       & Sci-Fi                                     \\\\\n\t 131172 & Closed Curtain (2013)                                  & (no genres listed)                         \\\\\n\t 131174 & Gentlemen (2014)                                       & Drama\\textbar{}Romance\\textbar{}Thriller                     \\\\\n\t 131176 & A Second Chance (2014)                                 & Drama                                      \\\\\n\t 131180 & Dead Rising: Watchtower (2015)                         & Action\\textbar{}Horror\\textbar{}Thriller                     \\\\\n\t 131231 & Standby (2014)                                         & Comedy\\textbar{}Romance                             \\\\\n\t 131237 & What Men Talk About (2010)                             & Comedy                                     \\\\\n\t 131239 & Three Quarter Moon (2011)                              & Comedy\\textbar{}Drama                               \\\\\n\t 131241 & Ants in the Pants (2000)                               & Comedy\\textbar{}Romance                             \\\\\n\t 131243 & Werner - Gekotzt wird später (2003)                    & Animation\\textbar{}Comedy                           \\\\\n\t 131248 & Brother Bear 2 (2006)                                  & Adventure\\textbar{}Animation\\textbar{}Children\\textbar{}Comedy\\textbar{}Fantasy\\\\\n\t 131250 & No More School (2000)                                  & Comedy                                     \\\\\n\t 131252 & Forklift Driver Klaus: The First Day on the Job (2001) & Comedy\\textbar{}Horror                              \\\\\n\t 131254 & Kein Bund für's Leben (2007)                           & Comedy                                     \\\\\n\t 131256 & Feuer, Eis \\& Dosenbier (2002)                          & Comedy                                     \\\\\n\t 131258 & The Pirates (2014)                                     & Adventure                                  \\\\\n\t 131260 & Rentun Ruusu (2001)                                    & (no genres listed)                         \\\\\n\t 131262 & Innocence (2014)                                       & Adventure\\textbar{}Fantasy\\textbar{}Horror                   \\\\\n\\end{tabular}\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Filtrar os filmes que contenham a palavra drama no titulo\n",
        "filmes_nomedrama <- subset(dados, grepl(\"Drama\", title))\n",
        "print(filmes_nomedrama)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zBJa7IwxL_Su",
        "outputId": "a968c492-285d-46dc-da6d-281d82c23b02"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "      movieId                                       title                genres\n",
            "7205     7316 Confessions of a Teenage Drama Queen (2004)                Comedy\n",
            "15413   78583                            Drama/Mex (2006)                 Drama\n",
            "16887   85387     Chang: A Drama of the Wilderness (1927) Adventure|Documentary\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Filtrar os filmes de genero Guerra\n",
        "filmes_guerra <- subset(dados, grepl(\"War\", genres))\n",
        "\n",
        "View(filmes_guerra)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "zVsybIDyMogs",
        "outputId": "e3e723c1-e6be-4ed8-90a9-d902a263de1d"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "      movieId\n",
              "41     41    \n",
              "73     73    \n",
              "109   110    \n",
              "150   151    \n",
              "154   155    \n",
              "156   157    \n",
              "160   161    \n",
              "213   214    \n",
              "264   266    \n",
              "333   336    \n",
              "337   340    \n",
              "353   356    \n",
              "386   389    \n",
              "462   465    \n",
              "463   466    \n",
              "470   473    \n",
              "524   527    \n",
              "626   632    \n",
              "640   647    \n",
              "658   665    \n",
              "659   666    \n",
              "678   688    \n",
              "738   750    \n",
              "748   760    \n",
              "765   777    \n",
              "808   822    \n",
              "881   897    \n",
              "904   920    \n",
              "909   925    \n",
              "930   946    \n",
              "⋮     ⋮      \n",
              "25861 122756 \n",
              "25892 122950 \n",
              "25899 123113 \n",
              "25913 123219 \n",
              "25926 123337 \n",
              "25929 123353 \n",
              "25961 123669 \n",
              "26000 124352 \n",
              "26009 124450 \n",
              "26104 125523 \n",
              "26141 125786 \n",
              "26261 126126 \n",
              "26325 126416 \n",
              "26332 126430 \n",
              "26405 126947 \n",
              "26436 127011 \n",
              "26468 127076 \n",
              "26548 127256 \n",
              "26584 127441 \n",
              "26606 127622 \n",
              "26607 127626 \n",
              "26666 128301 \n",
              "26960 129555 \n",
              "27056 130036 \n",
              "27087 130328 \n",
              "27088 130338 \n",
              "27098 130382 \n",
              "27119 130474 \n",
              "27245 131138 \n",
              "27258 131164 \n",
              "      title                                                                      \n",
              "41    Richard III (1995)                                                         \n",
              "73    Misérables, Les (1995)                                                     \n",
              "109   Braveheart (1995)                                                          \n",
              "150   Rob Roy (1995)                                                             \n",
              "154   Beyond Rangoon (1995)                                                      \n",
              "156   Canadian Bacon (1995)                                                      \n",
              "160   Crimson Tide (1995)                                                        \n",
              "213   Before the Rain (Pred dozhdot) (1994)                                      \n",
              "264   Legends of the Fall (1994)                                                 \n",
              "333   Walking Dead, The (1995)                                                   \n",
              "337   War, The (1994)                                                            \n",
              "353   Forrest Gump (1994)                                                        \n",
              "386   Colonel Chabert, Le (1994)                                                 \n",
              "462   Heaven & Earth (1993)                                                      \n",
              "463   Hot Shots! Part Deux (1993)                                                \n",
              "470   In the Army Now (1994)                                                     \n",
              "524   Schindler's List (1993)                                                    \n",
              "626   Land and Freedom (Tierra y libertad) (1995)                                \n",
              "640   Courage Under Fire (1996)                                                  \n",
              "658   Underground (1995)                                                         \n",
              "659   All Things Fair (Lust och fägring stor) (1995)                             \n",
              "678   Operation Dumbo Drop (1995)                                                \n",
              "738   Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)\n",
              "748   Stalingrad (1993)                                                          \n",
              "765   Pharaoh's Army (1995)                                                      \n",
              "808   Hedd Wyn (1992)                                                            \n",
              "881   For Whom the Bell Tolls (1943)                                             \n",
              "904   Gone with the Wind (1939)                                                  \n",
              "909   Golden Earrings (1947)                                                     \n",
              "930   To Be or Not to Be (1942)                                                  \n",
              "⋮     ⋮                                                                          \n",
              "25861 None But the Brave (1965)                                                  \n",
              "25892 Mare Nostrum (1926)                                                        \n",
              "25899 Springfield Rifle (1952)                                                   \n",
              "25913 The Adventures of Tartu (1943)                                             \n",
              "25926 I Accuse (1938)                                                            \n",
              "25929 The Hornet's Nest (2014)                                                   \n",
              "25961 See Here, Private Hargrove (1944)                                          \n",
              "26000 I Was Monty's Double (1958)                                                \n",
              "26009 Lady Killer (1937)                                                         \n",
              "26104 Time Limit (1957)                                                          \n",
              "26141 Burning Blue (2013)                                                        \n",
              "26261 Babette Goes to War (1959)                                                 \n",
              "26325 Stalag Luft (1993)                                                         \n",
              "26332 The Pacific (2010)                                                         \n",
              "26405 Carriage to Vienna (1966)                                                  \n",
              "26436 Under the Flag of the Rising Sun (1972)                                    \n",
              "26468 Defenders of Riga (2007)                                                   \n",
              "26548 The Old Gun (1975)                                                         \n",
              "26584 Last Days in Vietnam (2014)                                                \n",
              "26606 The House of Intrigue (1956)                                               \n",
              "26607 Under Ten Flags (1960)                                                     \n",
              "26666 Jungle Fighters (1961)                                                     \n",
              "26960 So Ends Our Night (1941)                                                   \n",
              "27056 Saints and Soldiers: The Void (2014)                                       \n",
              "27087 A Bright Shining Lie (1998)                                                \n",
              "27088 Silent Sonata (2011)                                                       \n",
              "27098 Mr. Pip (2012)                                                             \n",
              "27119 Suite Française (2015)                                                     \n",
              "27245 My Führer (2007)                                                           \n",
              "27258 Vietnam in HD (2011)                                                       \n",
              "      genres                     \n",
              "41    Drama|War                  \n",
              "73    Drama|War                  \n",
              "109   Action|Drama|War           \n",
              "150   Action|Drama|Romance|War   \n",
              "154   Adventure|Drama|War        \n",
              "156   Comedy|War                 \n",
              "160   Drama|Thriller|War         \n",
              "213   Drama|War                  \n",
              "264   Drama|Romance|War|Western  \n",
              "333   Drama|War                  \n",
              "337   Adventure|Drama|War        \n",
              "353   Comedy|Drama|Romance|War   \n",
              "386   Drama|Romance|War          \n",
              "462   Action|Drama|War           \n",
              "463   Action|Comedy|War          \n",
              "470   Comedy|War                 \n",
              "524   Drama|War                  \n",
              "626   Drama|War                  \n",
              "640   Action|Crime|Drama|War     \n",
              "658   Comedy|Drama|War           \n",
              "659   Drama|Romance|War          \n",
              "678   Action|Adventure|Comedy|War\n",
              "738   Comedy|War                 \n",
              "748   Drama|War                  \n",
              "765   War                        \n",
              "808   Drama|Romance|War          \n",
              "881   Adventure|Drama|Romance|War\n",
              "904   Drama|Romance|War          \n",
              "909   Adventure|Romance|War      \n",
              "930   Comedy|Drama|War           \n",
              "⋮     ⋮                          \n",
              "25861 Drama|War                  \n",
              "25892 War                        \n",
              "25899 Action|War|Western         \n",
              "25913 Drama|Romance|Thriller|War \n",
              "25926 Drama|Horror|Sci-Fi|War    \n",
              "25929 Documentary|War            \n",
              "25961 Comedy|Romance|War         \n",
              "26000 Drama|War                  \n",
              "26009 Drama|Romance|War          \n",
              "26104 Drama|Mystery|War          \n",
              "26141 Drama|Romance|War          \n",
              "26261 Comedy|War                 \n",
              "26325 Comedy|Drama|War           \n",
              "26332 Action|Adventure|Drama|War \n",
              "26405 Drama|War                  \n",
              "26436 Drama|Mystery|War          \n",
              "26468 Action|Drama|War           \n",
              "26548 Drama|Thriller|War         \n",
              "26584 Documentary|War            \n",
              "26606 Drama|War                  \n",
              "26607 Drama|War                  \n",
              "26666 Drama|War                  \n",
              "26960 Drama|War                  \n",
              "27056 Action|Drama|War           \n",
              "27087 Drama|War                  \n",
              "27088 Drama|Fantasy|War          \n",
              "27098 Drama|War                  \n",
              "27119 Drama|Romance|War          \n",
              "27245 Comedy|Drama|War           \n",
              "27258 War                        "
            ],
            "text/html": [
              "<table class=\"dataframe\">\n",
              "<caption>A data.frame: 1194 × 3</caption>\n",
              "<thead>\n",
              "\t<tr><th></th><th scope=col>movieId</th><th scope=col>title</th><th scope=col>genres</th></tr>\n",
              "\t<tr><th></th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;chr&gt;</th></tr>\n",
              "</thead>\n",
              "<tbody>\n",
              "\t<tr><th scope=row>41</th><td> 41</td><td>Richard III (1995)                                                         </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>73</th><td> 73</td><td>Misérables, Les (1995)                                                     </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>109</th><td>110</td><td>Braveheart (1995)                                                          </td><td>Action|Drama|War           </td></tr>\n",
              "\t<tr><th scope=row>150</th><td>151</td><td>Rob Roy (1995)                                                             </td><td>Action|Drama|Romance|War   </td></tr>\n",
              "\t<tr><th scope=row>154</th><td>155</td><td>Beyond Rangoon (1995)                                                      </td><td>Adventure|Drama|War        </td></tr>\n",
              "\t<tr><th scope=row>156</th><td>157</td><td>Canadian Bacon (1995)                                                      </td><td>Comedy|War                 </td></tr>\n",
              "\t<tr><th scope=row>160</th><td>161</td><td>Crimson Tide (1995)                                                        </td><td>Drama|Thriller|War         </td></tr>\n",
              "\t<tr><th scope=row>213</th><td>214</td><td>Before the Rain (Pred dozhdot) (1994)                                      </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>264</th><td>266</td><td>Legends of the Fall (1994)                                                 </td><td>Drama|Romance|War|Western  </td></tr>\n",
              "\t<tr><th scope=row>333</th><td>336</td><td>Walking Dead, The (1995)                                                   </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>337</th><td>340</td><td>War, The (1994)                                                            </td><td>Adventure|Drama|War        </td></tr>\n",
              "\t<tr><th scope=row>353</th><td>356</td><td>Forrest Gump (1994)                                                        </td><td>Comedy|Drama|Romance|War   </td></tr>\n",
              "\t<tr><th scope=row>386</th><td>389</td><td>Colonel Chabert, Le (1994)                                                 </td><td>Drama|Romance|War          </td></tr>\n",
              "\t<tr><th scope=row>462</th><td>465</td><td><span style=white-space:pre-wrap>Heaven &amp; Earth (1993)                                                      </span></td><td><span style=white-space:pre-wrap>Action|Drama|War           </span></td></tr>\n",
              "\t<tr><th scope=row>463</th><td>466</td><td>Hot Shots! Part Deux (1993)                                                </td><td>Action|Comedy|War          </td></tr>\n",
              "\t<tr><th scope=row>470</th><td>473</td><td>In the Army Now (1994)                                                     </td><td>Comedy|War                 </td></tr>\n",
              "\t<tr><th scope=row>524</th><td>527</td><td>Schindler's List (1993)                                                    </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>626</th><td>632</td><td>Land and Freedom (Tierra y libertad) (1995)                                </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>640</th><td>647</td><td>Courage Under Fire (1996)                                                  </td><td>Action|Crime|Drama|War     </td></tr>\n",
              "\t<tr><th scope=row>658</th><td>665</td><td>Underground (1995)                                                         </td><td>Comedy|Drama|War           </td></tr>\n",
              "\t<tr><th scope=row>659</th><td>666</td><td>All Things Fair (Lust och fägring stor) (1995)                             </td><td>Drama|Romance|War          </td></tr>\n",
              "\t<tr><th scope=row>678</th><td>688</td><td>Operation Dumbo Drop (1995)                                                </td><td>Action|Adventure|Comedy|War</td></tr>\n",
              "\t<tr><th scope=row>738</th><td>750</td><td>Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)</td><td>Comedy|War                 </td></tr>\n",
              "\t<tr><th scope=row>748</th><td>760</td><td>Stalingrad (1993)                                                          </td><td>Drama|War                  </td></tr>\n",
              "\t<tr><th scope=row>765</th><td>777</td><td>Pharaoh's Army (1995)                                                      </td><td>War                        </td></tr>\n",
              "\t<tr><th scope=row>808</th><td>822</td><td>Hedd Wyn (1992)                                                            </td><td>Drama|Romance|War          </td></tr>\n",
              "\t<tr><th scope=row>881</th><td>897</td><td>For Whom the Bell Tolls (1943)                                             </td><td>Adventure|Drama|Romance|War</td></tr>\n",
              "\t<tr><th scope=row>904</th><td>920</td><td>Gone with the Wind (1939)                                                  </td><td>Drama|Romance|War          </td></tr>\n",
              "\t<tr><th scope=row>909</th><td>925</td><td>Golden Earrings (1947)                                                     </td><td>Adventure|Romance|War      </td></tr>\n",
              "\t<tr><th scope=row>930</th><td>946</td><td>To Be or Not to Be (1942)                                                  </td><td>Comedy|Drama|War           </td></tr>\n",
              "\t<tr><th scope=row>⋮</th><td>⋮</td><td>⋮</td><td>⋮</td></tr>\n",
              "\t<tr><th scope=row>25861</th><td>122756</td><td>None But the Brave (1965)              </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>25892</th><td>122950</td><td>Mare Nostrum (1926)                    </td><td>War                       </td></tr>\n",
              "\t<tr><th scope=row>25899</th><td>123113</td><td>Springfield Rifle (1952)               </td><td>Action|War|Western        </td></tr>\n",
              "\t<tr><th scope=row>25913</th><td>123219</td><td>The Adventures of Tartu (1943)         </td><td>Drama|Romance|Thriller|War</td></tr>\n",
              "\t<tr><th scope=row>25926</th><td>123337</td><td>I Accuse (1938)                        </td><td>Drama|Horror|Sci-Fi|War   </td></tr>\n",
              "\t<tr><th scope=row>25929</th><td>123353</td><td>The Hornet's Nest (2014)               </td><td>Documentary|War           </td></tr>\n",
              "\t<tr><th scope=row>25961</th><td>123669</td><td>See Here, Private Hargrove (1944)      </td><td>Comedy|Romance|War        </td></tr>\n",
              "\t<tr><th scope=row>26000</th><td>124352</td><td>I Was Monty's Double (1958)            </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>26009</th><td>124450</td><td>Lady Killer (1937)                     </td><td>Drama|Romance|War         </td></tr>\n",
              "\t<tr><th scope=row>26104</th><td>125523</td><td>Time Limit (1957)                      </td><td>Drama|Mystery|War         </td></tr>\n",
              "\t<tr><th scope=row>26141</th><td>125786</td><td>Burning Blue (2013)                    </td><td>Drama|Romance|War         </td></tr>\n",
              "\t<tr><th scope=row>26261</th><td>126126</td><td>Babette Goes to War (1959)             </td><td>Comedy|War                </td></tr>\n",
              "\t<tr><th scope=row>26325</th><td>126416</td><td>Stalag Luft (1993)                     </td><td>Comedy|Drama|War          </td></tr>\n",
              "\t<tr><th scope=row>26332</th><td>126430</td><td>The Pacific (2010)                     </td><td>Action|Adventure|Drama|War</td></tr>\n",
              "\t<tr><th scope=row>26405</th><td>126947</td><td>Carriage to Vienna (1966)              </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>26436</th><td>127011</td><td>Under the Flag of the Rising Sun (1972)</td><td>Drama|Mystery|War         </td></tr>\n",
              "\t<tr><th scope=row>26468</th><td>127076</td><td>Defenders of Riga (2007)               </td><td>Action|Drama|War          </td></tr>\n",
              "\t<tr><th scope=row>26548</th><td>127256</td><td>The Old Gun (1975)                     </td><td>Drama|Thriller|War        </td></tr>\n",
              "\t<tr><th scope=row>26584</th><td>127441</td><td>Last Days in Vietnam (2014)            </td><td>Documentary|War           </td></tr>\n",
              "\t<tr><th scope=row>26606</th><td>127622</td><td>The House of Intrigue (1956)           </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>26607</th><td>127626</td><td>Under Ten Flags (1960)                 </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>26666</th><td>128301</td><td>Jungle Fighters (1961)                 </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>26960</th><td>129555</td><td>So Ends Our Night (1941)               </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>27056</th><td>130036</td><td>Saints and Soldiers: The Void (2014)   </td><td>Action|Drama|War          </td></tr>\n",
              "\t<tr><th scope=row>27087</th><td>130328</td><td>A Bright Shining Lie (1998)            </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>27088</th><td>130338</td><td>Silent Sonata (2011)                   </td><td>Drama|Fantasy|War         </td></tr>\n",
              "\t<tr><th scope=row>27098</th><td>130382</td><td>Mr. Pip (2012)                         </td><td>Drama|War                 </td></tr>\n",
              "\t<tr><th scope=row>27119</th><td>130474</td><td>Suite Française (2015)                 </td><td>Drama|Romance|War         </td></tr>\n",
              "\t<tr><th scope=row>27245</th><td>131138</td><td>My Führer (2007)                       </td><td>Comedy|Drama|War          </td></tr>\n",
              "\t<tr><th scope=row>27258</th><td>131164</td><td>Vietnam in HD (2011)                   </td><td>War                       </td></tr>\n",
              "</tbody>\n",
              "</table>\n"
            ],
            "text/markdown": "\nA data.frame: 1194 × 3\n\n| <!--/--> | movieId &lt;int&gt; | title &lt;chr&gt; | genres &lt;chr&gt; |\n|---|---|---|---|\n| 41 |  41 | Richard III (1995)                                                          | Drama|War                   |\n| 73 |  73 | Misérables, Les (1995)                                                      | Drama|War                   |\n| 109 | 110 | Braveheart (1995)                                                           | Action|Drama|War            |\n| 150 | 151 | Rob Roy (1995)                                                              | Action|Drama|Romance|War    |\n| 154 | 155 | Beyond Rangoon (1995)                                                       | Adventure|Drama|War         |\n| 156 | 157 | Canadian Bacon (1995)                                                       | Comedy|War                  |\n| 160 | 161 | Crimson Tide (1995)                                                         | Drama|Thriller|War          |\n| 213 | 214 | Before the Rain (Pred dozhdot) (1994)                                       | Drama|War                   |\n| 264 | 266 | Legends of the Fall (1994)                                                  | Drama|Romance|War|Western   |\n| 333 | 336 | Walking Dead, The (1995)                                                    | Drama|War                   |\n| 337 | 340 | War, The (1994)                                                             | Adventure|Drama|War         |\n| 353 | 356 | Forrest Gump (1994)                                                         | Comedy|Drama|Romance|War    |\n| 386 | 389 | Colonel Chabert, Le (1994)                                                  | Drama|Romance|War           |\n| 462 | 465 | Heaven &amp; Earth (1993)                                                       | Action|Drama|War            |\n| 463 | 466 | Hot Shots! Part Deux (1993)                                                 | Action|Comedy|War           |\n| 470 | 473 | In the Army Now (1994)                                                      | Comedy|War                  |\n| 524 | 527 | Schindler's List (1993)                                                     | Drama|War                   |\n| 626 | 632 | Land and Freedom (Tierra y libertad) (1995)                                 | Drama|War                   |\n| 640 | 647 | Courage Under Fire (1996)                                                   | Action|Crime|Drama|War      |\n| 658 | 665 | Underground (1995)                                                          | Comedy|Drama|War            |\n| 659 | 666 | All Things Fair (Lust och fägring stor) (1995)                              | Drama|Romance|War           |\n| 678 | 688 | Operation Dumbo Drop (1995)                                                 | Action|Adventure|Comedy|War |\n| 738 | 750 | Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) | Comedy|War                  |\n| 748 | 760 | Stalingrad (1993)                                                           | Drama|War                   |\n| 765 | 777 | Pharaoh's Army (1995)                                                       | War                         |\n| 808 | 822 | Hedd Wyn (1992)                                                             | Drama|Romance|War           |\n| 881 | 897 | For Whom the Bell Tolls (1943)                                              | Adventure|Drama|Romance|War |\n| 904 | 920 | Gone with the Wind (1939)                                                   | Drama|Romance|War           |\n| 909 | 925 | Golden Earrings (1947)                                                      | Adventure|Romance|War       |\n| 930 | 946 | To Be or Not to Be (1942)                                                   | Comedy|Drama|War            |\n| ⋮ | ⋮ | ⋮ | ⋮ |\n| 25861 | 122756 | None But the Brave (1965)               | Drama|War                  |\n| 25892 | 122950 | Mare Nostrum (1926)                     | War                        |\n| 25899 | 123113 | Springfield Rifle (1952)                | Action|War|Western         |\n| 25913 | 123219 | The Adventures of Tartu (1943)          | Drama|Romance|Thriller|War |\n| 25926 | 123337 | I Accuse (1938)                         | Drama|Horror|Sci-Fi|War    |\n| 25929 | 123353 | The Hornet's Nest (2014)                | Documentary|War            |\n| 25961 | 123669 | See Here, Private Hargrove (1944)       | Comedy|Romance|War         |\n| 26000 | 124352 | I Was Monty's Double (1958)             | Drama|War                  |\n| 26009 | 124450 | Lady Killer (1937)                      | Drama|Romance|War          |\n| 26104 | 125523 | Time Limit (1957)                       | Drama|Mystery|War          |\n| 26141 | 125786 | Burning Blue (2013)                     | Drama|Romance|War          |\n| 26261 | 126126 | Babette Goes to War (1959)              | Comedy|War                 |\n| 26325 | 126416 | Stalag Luft (1993)                      | Comedy|Drama|War           |\n| 26332 | 126430 | The Pacific (2010)                      | Action|Adventure|Drama|War |\n| 26405 | 126947 | Carriage to Vienna (1966)               | Drama|War                  |\n| 26436 | 127011 | Under the Flag of the Rising Sun (1972) | Drama|Mystery|War          |\n| 26468 | 127076 | Defenders of Riga (2007)                | Action|Drama|War           |\n| 26548 | 127256 | The Old Gun (1975)                      | Drama|Thriller|War         |\n| 26584 | 127441 | Last Days in Vietnam (2014)             | Documentary|War            |\n| 26606 | 127622 | The House of Intrigue (1956)            | Drama|War                  |\n| 26607 | 127626 | Under Ten Flags (1960)                  | Drama|War                  |\n| 26666 | 128301 | Jungle Fighters (1961)                  | Drama|War                  |\n| 26960 | 129555 | So Ends Our Night (1941)                | Drama|War                  |\n| 27056 | 130036 | Saints and Soldiers: The Void (2014)    | Action|Drama|War           |\n| 27087 | 130328 | A Bright Shining Lie (1998)             | Drama|War                  |\n| 27088 | 130338 | Silent Sonata (2011)                    | Drama|Fantasy|War          |\n| 27098 | 130382 | Mr. Pip (2012)                          | Drama|War                  |\n| 27119 | 130474 | Suite Française (2015)                  | Drama|Romance|War          |\n| 27245 | 131138 | My Führer (2007)                        | Comedy|Drama|War           |\n| 27258 | 131164 | Vietnam in HD (2011)                    | War                        |\n\n",
            "text/latex": "A data.frame: 1194 × 3\n\\begin{tabular}{r|lll}\n  & movieId & title & genres\\\\\n  & <int> & <chr> & <chr>\\\\\n\\hline\n\t41 &  41 & Richard III (1995)                                                          & Drama\\textbar{}War                  \\\\\n\t73 &  73 & Misérables, Les (1995)                                                      & Drama\\textbar{}War                  \\\\\n\t109 & 110 & Braveheart (1995)                                                           & Action\\textbar{}Drama\\textbar{}War           \\\\\n\t150 & 151 & Rob Roy (1995)                                                              & Action\\textbar{}Drama\\textbar{}Romance\\textbar{}War   \\\\\n\t154 & 155 & Beyond Rangoon (1995)                                                       & Adventure\\textbar{}Drama\\textbar{}War        \\\\\n\t156 & 157 & Canadian Bacon (1995)                                                       & Comedy\\textbar{}War                 \\\\\n\t160 & 161 & Crimson Tide (1995)                                                         & Drama\\textbar{}Thriller\\textbar{}War         \\\\\n\t213 & 214 & Before the Rain (Pred dozhdot) (1994)                                       & Drama\\textbar{}War                  \\\\\n\t264 & 266 & Legends of the Fall (1994)                                                  & Drama\\textbar{}Romance\\textbar{}War\\textbar{}Western  \\\\\n\t333 & 336 & Walking Dead, The (1995)                                                    & Drama\\textbar{}War                  \\\\\n\t337 & 340 & War, The (1994)                                                             & Adventure\\textbar{}Drama\\textbar{}War        \\\\\n\t353 & 356 & Forrest Gump (1994)                                                         & Comedy\\textbar{}Drama\\textbar{}Romance\\textbar{}War   \\\\\n\t386 & 389 & Colonel Chabert, Le (1994)                                                  & Drama\\textbar{}Romance\\textbar{}War          \\\\\n\t462 & 465 & Heaven \\& Earth (1993)                                                       & Action\\textbar{}Drama\\textbar{}War           \\\\\n\t463 & 466 & Hot Shots! Part Deux (1993)                                                 & Action\\textbar{}Comedy\\textbar{}War          \\\\\n\t470 & 473 & In the Army Now (1994)                                                      & Comedy\\textbar{}War                 \\\\\n\t524 & 527 & Schindler's List (1993)                                                     & Drama\\textbar{}War                  \\\\\n\t626 & 632 & Land and Freedom (Tierra y libertad) (1995)                                 & Drama\\textbar{}War                  \\\\\n\t640 & 647 & Courage Under Fire (1996)                                                   & Action\\textbar{}Crime\\textbar{}Drama\\textbar{}War     \\\\\n\t658 & 665 & Underground (1995)                                                          & Comedy\\textbar{}Drama\\textbar{}War           \\\\\n\t659 & 666 & All Things Fair (Lust och fägring stor) (1995)                              & Drama\\textbar{}Romance\\textbar{}War          \\\\\n\t678 & 688 & Operation Dumbo Drop (1995)                                                 & Action\\textbar{}Adventure\\textbar{}Comedy\\textbar{}War\\\\\n\t738 & 750 & Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) & Comedy\\textbar{}War                 \\\\\n\t748 & 760 & Stalingrad (1993)                                                           & Drama\\textbar{}War                  \\\\\n\t765 & 777 & Pharaoh's Army (1995)                                                       & War                        \\\\\n\t808 & 822 & Hedd Wyn (1992)                                                             & Drama\\textbar{}Romance\\textbar{}War          \\\\\n\t881 & 897 & For Whom the Bell Tolls (1943)                                              & Adventure\\textbar{}Drama\\textbar{}Romance\\textbar{}War\\\\\n\t904 & 920 & Gone with the Wind (1939)                                                   & Drama\\textbar{}Romance\\textbar{}War          \\\\\n\t909 & 925 & Golden Earrings (1947)                                                      & Adventure\\textbar{}Romance\\textbar{}War      \\\\\n\t930 & 946 & To Be or Not to Be (1942)                                                   & Comedy\\textbar{}Drama\\textbar{}War           \\\\\n\t⋮ & ⋮ & ⋮ & ⋮\\\\\n\t25861 & 122756 & None But the Brave (1965)               & Drama\\textbar{}War                 \\\\\n\t25892 & 122950 & Mare Nostrum (1926)                     & War                       \\\\\n\t25899 & 123113 & Springfield Rifle (1952)                & Action\\textbar{}War\\textbar{}Western        \\\\\n\t25913 & 123219 & The Adventures of Tartu (1943)          & Drama\\textbar{}Romance\\textbar{}Thriller\\textbar{}War\\\\\n\t25926 & 123337 & I Accuse (1938)                         & Drama\\textbar{}Horror\\textbar{}Sci-Fi\\textbar{}War   \\\\\n\t25929 & 123353 & The Hornet's Nest (2014)                & Documentary\\textbar{}War           \\\\\n\t25961 & 123669 & See Here, Private Hargrove (1944)       & Comedy\\textbar{}Romance\\textbar{}War        \\\\\n\t26000 & 124352 & I Was Monty's Double (1958)             & Drama\\textbar{}War                 \\\\\n\t26009 & 124450 & Lady Killer (1937)                      & Drama\\textbar{}Romance\\textbar{}War         \\\\\n\t26104 & 125523 & Time Limit (1957)                       & Drama\\textbar{}Mystery\\textbar{}War         \\\\\n\t26141 & 125786 & Burning Blue (2013)                     & Drama\\textbar{}Romance\\textbar{}War         \\\\\n\t26261 & 126126 & Babette Goes to War (1959)              & Comedy\\textbar{}War                \\\\\n\t26325 & 126416 & Stalag Luft (1993)                      & Comedy\\textbar{}Drama\\textbar{}War          \\\\\n\t26332 & 126430 & The Pacific (2010)                      & Action\\textbar{}Adventure\\textbar{}Drama\\textbar{}War\\\\\n\t26405 & 126947 & Carriage to Vienna (1966)               & Drama\\textbar{}War                 \\\\\n\t26436 & 127011 & Under the Flag of the Rising Sun (1972) & Drama\\textbar{}Mystery\\textbar{}War         \\\\\n\t26468 & 127076 & Defenders of Riga (2007)                & Action\\textbar{}Drama\\textbar{}War          \\\\\n\t26548 & 127256 & The Old Gun (1975)                      & Drama\\textbar{}Thriller\\textbar{}War        \\\\\n\t26584 & 127441 & Last Days in Vietnam (2014)             & Documentary\\textbar{}War           \\\\\n\t26606 & 127622 & The House of Intrigue (1956)            & Drama\\textbar{}War                 \\\\\n\t26607 & 127626 & Under Ten Flags (1960)                  & Drama\\textbar{}War                 \\\\\n\t26666 & 128301 & Jungle Fighters (1961)                  & Drama\\textbar{}War                 \\\\\n\t26960 & 129555 & So Ends Our Night (1941)                & Drama\\textbar{}War                 \\\\\n\t27056 & 130036 & Saints and Soldiers: The Void (2014)    & Action\\textbar{}Drama\\textbar{}War          \\\\\n\t27087 & 130328 & A Bright Shining Lie (1998)             & Drama\\textbar{}War                 \\\\\n\t27088 & 130338 & Silent Sonata (2011)                    & Drama\\textbar{}Fantasy\\textbar{}War         \\\\\n\t27098 & 130382 & Mr. Pip (2012)                          & Drama\\textbar{}War                 \\\\\n\t27119 & 130474 & Suite Française (2015)                  & Drama\\textbar{}Romance\\textbar{}War         \\\\\n\t27245 & 131138 & My Führer (2007)                        & Comedy\\textbar{}Drama\\textbar{}War          \\\\\n\t27258 & 131164 & Vietnam in HD (2011)                    & War                       \\\\\n\\end{tabular}\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Filtrar os filmes de genero Guerra ralizados no ano de 1992\n",
        "dados_1992 <- subset(filmes_guerra, grepl(\"\\\\(1992\\\\)\", title))\n",
        "View(dados_1992)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 349
        },
        "id": "6DMksSaWOo8_",
        "outputId": "d47c587b-1d48-43df-c446-625d05609627"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "      movieId title                                                   \n",
              "808      822  Hedd Wyn (1992)                                         \n",
              "1376    1408  Last of the Mohicans, The (1992)                        \n",
              "6914    7025  Midnight Clear, A (1992)                                \n",
              "7901    8582  Manufacturing Consent: Noam Chomsky and the Media (1992)\n",
              "9056   26791  Shining Through (1992)                                  \n",
              "9724   31547  Lessons of Darkness (Lektionen in Finsternis) (1992)    \n",
              "15901  80650  Diên Biên Phú (1992)                                    \n",
              "20740 101514  Ungentlemanly Act, An (1992)                            \n",
              "      genres                      \n",
              "808   Drama|Romance|War           \n",
              "1376  Action|Romance|War|Western  \n",
              "6914  Drama|War                   \n",
              "7901  Documentary|War             \n",
              "9056  Drama|Romance|Thriller|War  \n",
              "9724  Documentary|War             \n",
              "15901 Drama|War                   \n",
              "20740 Action|Documentary|Drama|War"
            ],
            "text/html": [
              "<table class=\"dataframe\">\n",
              "<caption>A data.frame: 8 × 3</caption>\n",
              "<thead>\n",
              "\t<tr><th></th><th scope=col>movieId</th><th scope=col>title</th><th scope=col>genres</th></tr>\n",
              "\t<tr><th></th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;chr&gt;</th></tr>\n",
              "</thead>\n",
              "<tbody>\n",
              "\t<tr><th scope=row>808</th><td>   822</td><td>Hedd Wyn (1992)                                         </td><td>Drama|Romance|War           </td></tr>\n",
              "\t<tr><th scope=row>1376</th><td>  1408</td><td>Last of the Mohicans, The (1992)                        </td><td>Action|Romance|War|Western  </td></tr>\n",
              "\t<tr><th scope=row>6914</th><td>  7025</td><td>Midnight Clear, A (1992)                                </td><td>Drama|War                   </td></tr>\n",
              "\t<tr><th scope=row>7901</th><td>  8582</td><td>Manufacturing Consent: Noam Chomsky and the Media (1992)</td><td>Documentary|War             </td></tr>\n",
              "\t<tr><th scope=row>9056</th><td> 26791</td><td>Shining Through (1992)                                  </td><td>Drama|Romance|Thriller|War  </td></tr>\n",
              "\t<tr><th scope=row>9724</th><td> 31547</td><td>Lessons of Darkness (Lektionen in Finsternis) (1992)    </td><td>Documentary|War             </td></tr>\n",
              "\t<tr><th scope=row>15901</th><td> 80650</td><td>Diên Biên Phú (1992)                                    </td><td>Drama|War                   </td></tr>\n",
              "\t<tr><th scope=row>20740</th><td>101514</td><td>Ungentlemanly Act, An (1992)                            </td><td>Action|Documentary|Drama|War</td></tr>\n",
              "</tbody>\n",
              "</table>\n"
            ],
            "text/markdown": "\nA data.frame: 8 × 3\n\n| <!--/--> | movieId &lt;int&gt; | title &lt;chr&gt; | genres &lt;chr&gt; |\n|---|---|---|---|\n| 808 |    822 | Hedd Wyn (1992)                                          | Drama|Romance|War            |\n| 1376 |   1408 | Last of the Mohicans, The (1992)                         | Action|Romance|War|Western   |\n| 6914 |   7025 | Midnight Clear, A (1992)                                 | Drama|War                    |\n| 7901 |   8582 | Manufacturing Consent: Noam Chomsky and the Media (1992) | Documentary|War              |\n| 9056 |  26791 | Shining Through (1992)                                   | Drama|Romance|Thriller|War   |\n| 9724 |  31547 | Lessons of Darkness (Lektionen in Finsternis) (1992)     | Documentary|War              |\n| 15901 |  80650 | Diên Biên Phú (1992)                                     | Drama|War                    |\n| 20740 | 101514 | Ungentlemanly Act, An (1992)                             | Action|Documentary|Drama|War |\n\n",
            "text/latex": "A data.frame: 8 × 3\n\\begin{tabular}{r|lll}\n  & movieId & title & genres\\\\\n  & <int> & <chr> & <chr>\\\\\n\\hline\n\t808 &    822 & Hedd Wyn (1992)                                          & Drama\\textbar{}Romance\\textbar{}War           \\\\\n\t1376 &   1408 & Last of the Mohicans, The (1992)                         & Action\\textbar{}Romance\\textbar{}War\\textbar{}Western  \\\\\n\t6914 &   7025 & Midnight Clear, A (1992)                                 & Drama\\textbar{}War                   \\\\\n\t7901 &   8582 & Manufacturing Consent: Noam Chomsky and the Media (1992) & Documentary\\textbar{}War             \\\\\n\t9056 &  26791 & Shining Through (1992)                                   & Drama\\textbar{}Romance\\textbar{}Thriller\\textbar{}War  \\\\\n\t9724 &  31547 & Lessons of Darkness (Lektionen in Finsternis) (1992)     & Documentary\\textbar{}War             \\\\\n\t15901 &  80650 & Diên Biên Phú (1992)                                     & Drama\\textbar{}War                   \\\\\n\t20740 & 101514 & Ungentlemanly Act, An (1992)                             & Action\\textbar{}Documentary\\textbar{}Drama\\textbar{}War\\\\\n\\end{tabular}\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Relatório:\n",
        "Foi realizado o filtro de filmes que contenham a palavra drama no titulo.\n",
        "(3 resultados)\n",
        "Posteriormente foi realizado um filtro de filmes de genero War\n",
        "(1194 resultados)\n",
        "A partir dessa análise foi realizado um segundo filtro para listar apenas os filmes de genero War realizados no ano de 1992\n",
        "(8 resultados)\n",
        "Os resultados foram apresentados a partir do comando View."
      ],
      "metadata": {
        "id": "Dg7EAH661M_d"
      }
    }
  ]
}