# -*- coding: utf-8 -*-
"""TAREFA DIA 5/04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jwRkKSzY-Krbp0xQ1KjYAJmV-zlpb17
"""

install.packages("ggplot2")
library(ggplot2)

dados <- data.frame
x = 1:

read.csv("movie.csv")

dados <- data.frame (
  x = 1:27278
  y = c( 1, "", 27278)
)

print(dados)

dados <- read.csv("movie.csv")

# Este código visualiza as primeira linhas
head(dados)

# Este banco de dados visualiza o total de  linhas movieId são 27278 linhas e 3 colunas
View(dados)

genres_ordenados <- dados[order(dados$genres),]
print (genres_ordenados)

contagem_genero <- table(unlist(strsplit(dados$genres, "|")))
print(contagem_genero)