# -*- coding: utf-8 -*-
"""Curso Senai_Gráficos_1 aula_ Regressão Linear

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nninMlLoSNkt1N2YTbqw1QHl8cOsUhdh
"""

install.packages("ggplot2")
library(ggplot2)

install.packages("tidyr")
library(tidyr)

install.packages("dplyr")
library(dplyr)

install.packages("caret")
library(caret)

dados <- data.frame ("movies_data")

# dados
x = popularidade
y = movies_data

dados <- read.csv("movie.csv")

head(dados)

# Ver os dados
print (dados)

#ver mais de 200 movies
options(max.print = 200)

View(dados)

#criar data.frame com os dados fornecidos
dados <- data.frame(
  movieId = c(1, 2, 3, 4, 5, 6),
  title = c("2010: Moby Dick (2010)", "2 Days in New York (2012)", "2010: Moby Dick (2010)", "Terminal USA (1993)", "Drive, He Said (1971)", "Treasure Island (2012)"),
  genres = c("Adventure", "Action", "Comedy", "Drama", "Action|Adventure|Thriller", "no genres listed")
)

print(dados)

dados_2010 <- subset(dados, grepl("\\(2010)\\)", title))

head(dados_2010)

#Acrescentar mais cinco títulos com o ano de 2024
novos_titulos <- c("Para onde vou (2024)", "SENAI não(2024)", "Palmeiras não tem mundial (2022)", "Sextou (2024)", "R é  legal (2024)"
)
novos_genres <- c(
  "Action|Adventure",
  "Comedy|Romance",
  "Drama|Thriller",
  "Fantasy|Sci-Fi",
  "Horror|Mystery"
)
dados_adicionais <- data.frame(movieId = max(dados$movieId)+
  1:max(length(novos_titulos)),
title = novos_titulos,
genres = novos_titulos)

print(dados_adicionais)

# Combinar os dados originais com dados adicionais
dados <- rbind(dados, dados_adicionais)

print(dados)

head(dados)

head(dados_2010)

#Extrair os dados de 1995
dados_2024 <- subset(dados, grepl("\\(2024\\)", title))

head(dados_2024)

# Filtrar os filmes que contenham "Action" no título
filmes_comedia <- subset(dados, grepl("Action", genres))

print(filmes_comedia)

# Ordenar os filmes por Título em ordem crescente
filmes_ordenados <- dados[order(dados$title),]
print (filmes_ordenados)

# Calcular a contagem de filmes por gênero
contagem_genero <- table(unlist(strsplit(dados$genres, "|")))
print(contagem_genero)

#Criar um data frame de avaliações manualmente
avaliacoes <- data.frame (
  movieId = c(1, 2, 3, 4, 5),
  rating = c(4.5, 3.0, 2.5, 4.0, 5.0)
)

print(avaliacoes)

#Supondo que você tenha outro dataframe chamado "avaliacoes"com avaliacoes de filmes

# Juntar os datag=frames "dados" e "avaliacoes" com base na coluna "moviedId"
dados_avaliacoes <- merge(dados, avaliacoes, by = "movieId")
print(dados_avaliacoes)

# Adcionar uma nova  coluna chamada "ano_lancamento" contenco apenas o ano do título
dados$ano_lacamento <- as.integer(gsub(",*\\((\\d+)\\)", "\\1", dados$title))
print(dados)

# Converter o dataframe para o formato longo usando a função gather() do pacote tidyr
install.packages("tidyr")
library(tidyr)