# -*- coding: utf-8 -*-
"""TRABALHO FINAL 1 PARTE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5tKtK-9SuYYZGHWGaLGFgBqge945m8Z
"""

# Usando a função names()
colunas <- names(dados)
print(colunas)

# Visualizar as primeiras 5 linhas do resultado
print(head(dados, 2))

# Verificar a estrutura do dataframe
str(dados)

install.packages("ggplot2")

library(ggplot2)

dados <- data.frame("dados_gasolina.txt")

head("dados_gasolina.txt")

print(dados)

read.csv2("dados_gasolina.txt")

head(dados)

View(dados)

dados <- read.csv2("dados_gasolina.txt")

head(dados)

View(dados)

print(dados)

# Calcular a média dos preços
media_Valor_de_Venda <- mean(dados$rating, na.rm = TRUE)
print(media_Valor_de_Venda)

# Criar um gráfico de histograma da contagem de filmes por ano de lançamento
grafico_histogram_estado <- ggplot(data = dados, aes(x = Estado )) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(title = "Valor_de_Venda", x = "Estado", y = "valor_de_venda")

# Imprimir o gráfico
print(grafico_histogram_estado)